### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by ghost** [FelixMo42/eco4x#1]
Enable GH pages to the master branch so the game can be played from `https://FelixMo42.github.io/maze_of_monsters/`

;)

**Comment by FelixMo42** [comment]
Does that work for React? I think I need to host it from a node server.

**Comment by ghost** [comment]
Ah, not for react then. What is the purpose of /public? I thought if this was a static front-end, you could use gh-pages

**Comment by FelixMo42** [comment]
I could do it (as long as my website is static), but I would need to pre
compile it. Which I'm to lazy to do write now.
